### ISSUE TITLE
the newest release of MakiePublication.jl

### ISSUE THREAD

**Issue by wssuzb** [liuyxpp/MakiePublication.jl#8]
Dear Professor Liu,

Very nice plot package for Julia. 

Recently I used your package for plotting, and I would like to adjust the `heightwidthratio` parameter in the function `theme_web()`. However, it is only available in the version by using `add https://github.com/liuyxpp/MakiePublication.jl.git`, and `add MakiePublication` does not have `heightwidthratio` because it seems to be an old version.

I was wondering if it's convenient for you to release the newest version of MakiePublication.jl? Many thanks in advance.

Best wishes,
Zhen-Bo su

**Comment by liuyxpp** [comment]
Done & Enjoy!
